version: '3.4'

# You need to start it with the following CLI command:
# docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build

services:
    sqldata:
        image: 'mcr.microsoft.com/mssql/server:2017-latest'

    user.api:
        image: 'user.api:${PLATFORM:-linux}-${TAG:-latest}'
        build:
            context: .
            dockerfile: src/Services/User.API/Dockerfile
        depends_on:
            - sqldata

    chat.vuejsapp:
        image: 'chatvuejsapp:${PLATFORM:-linux}-${TAG:-latest}'
        build:
          context: .
          dockerfile: src/Presentation/Chat.VuejsApp/Dockerfile
        depends_on:
          - user.api